
// Theme configuration for the application
const themes = {
  default: {
    name: "Default",
    colors: {
      sidebarBg: "#4A154B",
      sidebarText: "#FFFFFF",
      sidebarHover: "#3F0E3F",
      sidebarBorder: "rgba(255, 255, 255, 0.1)",
      chatBg: "#FFFFFF",
      chatText: "#1D1C1D",
      chatInputBg: "#F8F8F8",
      chatInputBorder: "#DDDDDD",
      headerBg: "#FFFFFF",
      headerText: "#1D1C1D",
      accent: "#1264A3",
      accentHover: "#0B4C8C",
      mentionBg: "#ECF5FB",
      mentionColor: "#1264A3",
      link: "#1264A3",
      divider: "#EEEEEE",
      buttonBg: "#007a5a",
      buttonText: "#FFFFFF",
      buttonHoverBg: "#148567",
      modalBg: "#FFFFFF",
      modalText: "#1D1C1D",
      modalBorder: "#DDDDDD",
    }
  },
  dark: {
    name: "Dark",
    colors: {
      sidebarBg: "#1D1B1D",
      sidebarText: "#FFFFFF",
      sidebarHover: "#2C2C2C",
      sidebarBorder: "rgba(255, 255, 255, 0.1)",
      chatBg: "#2D2C2D",
      chatText: "#E8E8E8",
      chatInputBg: "#3F3F3F",
      chatInputBorder: "#5F5F5F",
      headerBg: "#1D1B1D",
      headerText: "#E8E8E8",
      accent: "#1264A3",
      accentHover: "#0B4C8C",
      mentionBg: "#0F2E43",
      mentionColor: "#36C5F0",
      link: "#36C5F0",
      divider: "#3F3F3F",
      buttonBg: "#007a5a",
      buttonText: "#FFFFFF",
      buttonHoverBg: "#148567",
      modalBg: "#2D2C2D",
      modalText: "#E8E8E8",
      modalBorder: "#5F5F5F",
    }
  },
  aubergine: {
    name: "Aubergine",
    colors: {
      sidebarBg: "#3F0E40",
      sidebarText: "#FFFFFF",
      sidebarHover: "#350D36",
      sidebarBorder: "rgba(255, 255, 255, 0.1)",
      chatBg: "#FFFFFF",
      chatText: "#1D1C1D",
      chatInputBg: "#F8F8F8",
      chatInputBorder: "#DDDDDD",
      headerBg: "#3F0E40",
      headerText: "#FFFFFF",
      accent: "#CD2553",
      accentHover: "#A11F48",
      mentionBg: "#FFF8F9",
      mentionColor: "#CD2553",
      link: "#1264A3",
      divider: "#EEEEEE",
      buttonBg: "#CD2553",
      buttonText: "#FFFFFF",
      buttonHoverBg: "#A11F48",
      modalBg: "#FFFFFF",
      modalText: "#1D1C1D",
      modalBorder: "#DDDDDD",
    }
  },
  clementine: {
    name: "Clementine",
    colors: {
      sidebarBg: "#A4320B",
      sidebarText: "#FFFFFF",
      sidebarHover: "#8C2A09",
      sidebarBorder: "rgba(255, 255, 255, 0.1)",
      chatBg: "#FFFFFF",
      chatText: "#1D1C1D",
      chatInputBg: "#F8F8F8",
      chatInputBorder: "#DDDDDD",
      headerBg: "#A4320B",
      headerText: "#FFFFFF",
      accent: "#F26130",
      accentHover: "#D45428",
      mentionBg: "#FFF1EC",
      mentionColor: "#F26130",
      link: "#1264A3",
      divider: "#EEEEEE",
      buttonBg: "#F26130",
      buttonText: "#FFFFFF",
      buttonHoverBg: "#D45428",
      modalBg: "#FFFFFF",
      modalText: "#1D1C1D",
      modalBorder: "#DDDDDD",
    }
  },
  banana: {
    name: "Banana",
    colors: {
      sidebarBg: "#875A12",
      sidebarText: "#FFFFFF",
      sidebarHover: "#724B0F",
      sidebarBorder: "rgba(255, 255, 255, 0.1)",
      chatBg: "#FFFDF5",
      chatText: "#1D1C1D",
      chatInputBg: "#FFFFFF",
      chatInputBorder: "#DDDDDD",
      headerBg: "#875A12",
      headerText: "#FFFFFF",
      accent: "#E2B307",
      accentHover: "#C79E06",
      mentionBg: "#FFFADC",
      mentionColor: "#875A12",
      link: "#1264A3",
      divider: "#EEEEEE",
      buttonBg: "#E2B307",
      buttonText: "#FFFFFF",
      buttonHoverBg: "#C79E06",
      modalBg: "#FFFFFF",
      modalText: "#1D1C1D",
      modalBorder: "#DDDDDD",
    }
  },
  lagoon: {
    name: "Lagoon",
    colors: {
      sidebarBg: "#0C5E70",
      sidebarText: "#FFFFFF",
      sidebarHover: "#0A4E5D",
      sidebarBorder: "rgba(255, 255, 255, 0.1)",
      chatBg: "#F5FCFF",
      chatText: "#1D1C1D",
      chatInputBg: "#FFFFFF",
      chatInputBorder: "#DDDDDD",
      headerBg: "#0C5E70",
      headerText: "#FFFFFF",
      accent: "#1A9BB5",
      accentHover: "#16849C",
      mentionBg: "#E5F7FB",
      mentionColor: "#1A9BB5",
      link: "#1A9BB5",
      divider: "#EEEEEE",
      buttonBg: "#1A9BB5",
      buttonText: "#FFFFFF",
      buttonHoverBg: "#16849C",
      modalBg: "#FFFFFF",
      modalText: "#1D1C1D",
      modalBorder: "#DDDDDD",
    }
  },
  mintChip: {
    name: "Mint Chip",
    colors: {
      sidebarBg: "#023020",
      sidebarText: "#FFFFFF",
      sidebarHover: "#01271A",
      sidebarBorder: "rgba(255, 255, 255, 0.1)",
      chatBg: "#F5FFF7",
      chatText: "#1D1C1D",
      chatInputBg: "#FFFFFF",
      chatInputBorder: "#DDDDDD",
      headerBg: "#023020",
      headerText: "#FFFFFF",
      accent: "#25A969",
      accentHover: "#1F8D56",
      mentionBg: "#E5F7EF",
      mentionColor: "#25A969",
      link: "#25A969",
      divider: "#EEEEEE",
      buttonBg: "#25A969",
      buttonText: "#FFFFFF",
      buttonHoverBg: "#1F8D56",
      modalBg: "#FFFFFF",
      modalText: "#1D1C1D",
      modalBorder: "#DDDDDD",
    }
  },
  blueberry: {
    name: "Blueberry",
    colors: {
      sidebarBg: "#1A1D31",
      sidebarText: "#FFFFFF",
      sidebarHover: "#141628",
      sidebarBorder: "rgba(255, 255, 255, 0.1)",
      chatBg: "#F5F7FF",
      chatText: "#1D1C1D",
      chatInputBg: "#FFFFFF",
      chatInputBorder: "#DDDDDD",
      headerBg: "#1A1D31",
      headerText: "#FFFFFF",
      accent: "#3F51B5",
      accentHover: "#32408F",
      mentionBg: "#E8EAF6",
      mentionColor: "#3F51B5",
      link: "#3F51B5",
      divider: "#EEEEEE",
      buttonBg: "#3F51B5",
      buttonText: "#FFFFFF",
      buttonHoverBg: "#32408F",
      modalBg: "#FFFFFF",
      modalText: "#1D1C1D",
      modalBorder: "#DDDDDD",
    }
  },
  raspberry: {
    name: "Raspberry",
    colors: {
      sidebarBg: "#7D092F",
      sidebarText: "#FFFFFF",
      sidebarHover: "#690827",
      sidebarBorder: "rgba(255, 255, 255, 0.1)",
      chatBg: "#FFF5F7",
      chatText: "#1D1C1D",
      chatInputBg: "#FFFFFF",
      chatInputBorder: "#DDDDDD",
      headerBg: "#7D092F",
      headerText: "#FFFFFF",
      accent: "#E91E63",
      accentHover: "#C2185B",
      mentionBg: "#FCE4EC",
      mentionColor: "#E91E63",
      link: "#E91E63",
      divider: "#EEEEEE",
      buttonBg: "#E91E63",
      buttonText: "#FFFFFF",
      buttonHoverBg: "#C2185B",
      modalBg: "#FFFFFF",
      modalText: "#1D1C1D",
      modalBorder: "#DDDDDD",
    }
  },
  forest: {
    name: "Forest",
    colors: {
      sidebarBg: "#0E3B2C",
      sidebarText: "#FFFFFF",
      sidebarHover: "#0A2F23",
      sidebarBorder: "rgba(255, 255, 255, 0.1)",
      chatBg: "#F9FFF9",
      chatText: "#1D1C1D",
      chatInputBg: "#FFFFFF",
      chatInputBorder: "#DDDDDD",
      headerBg: "#0E3B2C",
      headerText: "#FFFFFF",
      accent: "#2BAC76",
      accentHover: "#228F61",
      mentionBg: "#E6F7EF",
      mentionColor: "#2BAC76",
      link: "#2BAC76",
      divider: "#EEEEEE",
      buttonBg: "#2BAC76",
      buttonText: "#FFFFFF",
      buttonHoverBg: "#228F61",
      modalBg: "#FFFFFF",
      modalText: "#1D1C1D",
      modalBorder: "#DDDDDD",
    }
  },
  midnight: {
    name: "Midnight",
    colors: {
      sidebarBg: "#121212",
      sidebarText: "#EEEEEE",
      sidebarHover: "#1E1E1E",
      sidebarBorder: "rgba(255, 255, 255, 0.1)",
      chatBg: "#1E1E1E",
      chatText: "#EEEEEE",
      chatInputBg: "#2D2D2D",
      chatInputBorder: "#444444",
      headerBg: "#121212",
      headerText: "#EEEEEE",
      accent: "#9147FF",
      accentHover: "#7D39DF",
      mentionBg: "#2D1E40",
      mentionColor: "#9147FF",
      link: "#9147FF",
      divider: "#2D2D2D",
      buttonBg: "#9147FF",
      buttonText: "#FFFFFF",
      buttonHoverBg: "#7D39DF",
      modalBg: "#1E1E1E",
      modalText: "#EEEEEE",
      modalBorder: "#444444",
    }
  },
  custom: {
    name: "Custom",
    colors: {
      sidebarBg: "#1264A3",
      sidebarText: "#FFFFFF",
      sidebarHover: "#0B4C8C",
      sidebarBorder: "rgba(255, 255, 255, 0.1)",
      chatBg: "#FFFFFF",
      chatText: "#1D1C1D",
      chatInputBg: "#F8F8F8",
      chatInputBorder: "#DDDDDD",
      headerBg: "#1264A3",
      headerText: "#FFFFFF",
      accent: "#1A1D31",
      accentHover: "#13162A",
      mentionBg: "#ECF5FB",
      mentionColor: "#1264A3",
      link: "#1264A3",
      divider: "#EEEEEE",
      buttonBg: "#1A1D31",
      buttonText: "#FFFFFF",
      buttonHoverBg: "#13162A",
      modalBg: "#FFFFFF",
      modalText: "#1D1C1D",
      modalBorder: "#DDDDDD",
    }
  },
};

export default themes;
